# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/product_prices' do
  # This should return the minimal set of attributes required to create a valid
  # ProductPrice. As you add validations to ProductPrice, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      ProductPrice.create! valid_attributes
      get product_prices_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      product_price = ProductPrice.create! valid_attributes
      get product_price_url(product_price)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_product_price_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      product_price = ProductPrice.create! valid_attributes
      get edit_product_price_url(product_price)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new ProductPrice' do
        expect do
          post product_prices_url, params: { product_price: valid_attributes }
        end.to change(ProductPrice, :count).by(1)
      end

      it 'redirects to the created product_price' do
        post product_prices_url, params: { product_price: valid_attributes }
        expect(response).to redirect_to(product_price_url(ProductPrice.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new ProductPrice' do
        expect do
          post product_prices_url, params: { product_price: invalid_attributes }
        end.not_to change(ProductPrice, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post product_prices_url, params: { product_price: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested product_price' do
        product_price = ProductPrice.create! valid_attributes
        patch product_price_url(product_price), params: { product_price: new_attributes }
        product_price.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the product_price' do
        product_price = ProductPrice.create! valid_attributes
        patch product_price_url(product_price), params: { product_price: new_attributes }
        product_price.reload
        expect(response).to redirect_to(product_price_url(product_price))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        product_price = ProductPrice.create! valid_attributes
        patch product_price_url(product_price), params: { product_price: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested product_price' do
      product_price = ProductPrice.create! valid_attributes
      expect do
        delete product_price_url(product_price)
      end.to change(ProductPrice, :count).by(-1)
    end

    it 'redirects to the product_prices list' do
      product_price = ProductPrice.create! valid_attributes
      delete product_price_url(product_price)
      expect(response).to redirect_to(product_prices_url)
    end
  end
end
